version: "3"
services:
  structurizr:
    image: structurizr/lite:latest
    volumes:
      - ./docs:/usr/local/structurizr
    ports:
      - "8080:8080"
  queue:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - queue_data:/data
    command: redis-server --appendonly yes
  request_handler:
    build: request_handler
    depends_on:
      - queue
    volumes:
      - .:/usr/src/minting_server/request_handler
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=queue
      - REDIS_PORT=6379
      - NODE_ENV=development
  request_processor:
    build: ./request_processor
    depends_on:
      - queue
    environment:
      - REDIS_HOST=queue
      - REDIS_PORT=6379
      - NODE_ENV=development
volumes:
  queue_data:
