version: '3'
services:
  structurizr:
    image: structurizr/lite:latest
    volumes:
      - ./docs:/usr/local/structurizr
    ports:
      - "8080:8080"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  app:
    build: request_handler
    depends_on:
      - redis
    volumes:
      - .:/usr/src/minting_server/app
    ports:
      - "3000:3000"
volumes:
  redis_data:
