version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  app:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/usr/src/minting_server/app
    ports:
      - "3000:3000"
volumes:
  redis_data:
