# This is an example of a smart contract configuration file
# based on the move/example_contract of the project's root dir.
smartContractFunctions:
  - name: "mint_nft" # The name of the function in the smart contract
    argumentTypes: ["object"] # The types of arguments that the function takes
    typeArguments: [] # The type arguments if generic types are used
  # You can specify more functions here e.g.
  - name: "transfer::public_transfer"
    argumentTypes: ["object", "address"]
    typeArguments:
      [
        "0x14ab6ea486e2d55710243637b270d707e4878d256c44f835db2112c85385cb22::contract_example::ExampleNFT",
      ]
