# This is an examle of a smart contract configuration file
# based on the move/example_contract of the project's root dir.
smart_contract_functions:
  - name: "mint_nft"
    types_of_arguments: ["object"]
